stages:
    - deploy

deploy_to_github:
    stage: deploy
    script:
        - git remote add github https://github.com/Chosamee/webrtc-ssafy.git
        - git push github HEAD:master --force
    only:
        - master
