version: "3"

services:
    backend:
        image: ${BACK_IMAGE_NAME}:${BUILD_NUMBER}
        networks:
            - digle-network

    frontend:
        image: ${FRONT_IMAGE_NAME}:${BUILD_NUMBER}
        networks:
            - digle-network
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
            - frontend
        networks:
            - digle-network

networks:
    digle-network:
        driver: bridge
