services:
    backend:
        image: ${BACK_IMAGE_NAME}:${BUILD_NUMBER}
        ports:
            - "8000:8000"
        depends_on:
            - frontend
        volumes:
            - /home/ubuntu/digle_storage:/app/storage
    frontend:
        image: ${FRONT_IMAGE_NAME}:${BUILD_NUMBER}
        ports:
            - "3000:3000"
