"""empty message

Revision ID: 905eb17dc689
Revises: 
Create Date: 2024-02-12 22:36:53.666702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "905eb17dc689"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("users", sa.Column("embedded_profile", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "embedded_profile")
    op.drop_constraint(None, "room_info", type_="foreignkey")
    op.create_foreign_key("room_info_host_id_fkey", "room_info", "users", ["host_id"], ["id"])
    op.create_table(
        "room_participants",
        sa.Column("room_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["room_id"], ["room_info.id"], name="room_participants_room_id_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="room_participants_user_id_fkey"),
        sa.PrimaryKeyConstraint("room_id", "user_id", name="room_participants_pkey"),
    )
    # ### end Alembic commands ###
